<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Enums\ProductStatus;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'sort_order'       => 1,
                'category_id'      => 1,
                'title'            => 'Hydrating Face Essence',
                'slug'             => 'hydrating-face-essence',
                'description'      => 'A gentle hydrating cleanser with ceramides and hyaluronic acid.',
                'price'            => 12,
                'sale_price'       => null,
                'product_types'    => ['Dry', 'Sensitive'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/cerave-cleanser',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 2,
                'category_id'      => 4,
                'title'            => 'Gentle Cleansing Oil',
                'slug'             => 'gentle-cleansing-oil',
                'description'      => 'Brightening serum for reducing blemishes and oiliness.',
                'price'            => 13,
                'sale_price'       => null,
                'product_types'    => ['Oily', 'Normal'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/niacinamide-serum',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 3,
                'category_id'      => 7,
                'title'            => 'Brightening Serum',
                'slug'             => 'brightening-serum',
                'description'      => 'Broad spectrum high protection sunscreen for face and body.',
                'price'            => 10,
                'sale_price'       => 8,
                'product_types'    => ['All Skin Types'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/anthelios-sunscreen',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 4,
                'category_id'      => 2,
                'title'            => 'Moisturizing Night Cream',
                'slug'             => 'moisturizing-night-cream',
                'description'      => 'Rich night cream for hydration and skin repair.',
                'price'            => 10,
                'sale_price'       => 8,
                'product_types'    => ['Dry', 'Sensitive'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/anthelios-sunscreen',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 5,
                'category_id'      => 3,
                'title'            => 'Acne Control Mask',
                'slug'             => 'acne-control-mask',
                'description'      => 'Mask for controlling acne and excess oil.',
                'price'            => 10,
                'sale_price'       => 8,
                'product_types'    => ['Oily', 'Combination'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/anthelios-sunscreen',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 6,
                'category_id'      => 7,
                'title'            => 'SPF 50 Sunscreen',
                'slug'             => 'spf-50-sunscreen',
                'description'      => 'Broad spectrum high protection sunscreen for face and body.',
                'price'            => 10,
                'sale_price'       => 8,
                'product_types'    => ['Oily', 'Combination'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/anthelios-sunscreen',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 7,
                'category_id'      => 5,
                'title'            => 'Soothing Rose Toner',
                'slug'             => 'soothing-rose-toner',
                'description'      => 'A refreshing toner that hydrates and calms irritated skin.',
                'price'            => 9,
                'sale_price'       => null,
                'product_types'    => ['Dry', 'Sensitive'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/rose-toner',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 8,
                'category_id'      => 4,
                'title'            => 'Vitamin C Glow Serum',
                'slug'             => 'vitamin-c-glow-serum',
                'description'      => 'A brightening serum enriched with 15% Vitamin C for glowing skin.',
                'price'            => 15,
                'sale_price'       => 12,
                'product_types'    => ['All Skin Types'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/vitamin-c-serum',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 9,
                'category_id'      => 6,
                'title'            => 'Ultra Hydration Gel Cream',
                'slug'             => 'ultra-hydration-gel-cream',
                'description'      => 'Lightweight gel cream that hydrates without greasiness.',
                'price'            => 11,
                'sale_price'       => null,
                'product_types'    => ['Oily', 'Combination'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/hydration-gel',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 10,
                'category_id'      => 1,
                'title'            => 'Foaming Deep Cleanser',
                'slug'             => 'foaming-deep-cleanser',
                'description'      => 'A foaming cleanser that removes oil and impurities.',
                'price'            => 9,
                'sale_price'       => null,
                'product_types'    => ['Oily', 'Normal'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/deep-cleanser',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 11,
                'category_id'      => 3,
                'title'            => 'Detox Charcoal Mask',
                'slug'             => 'detox-charcoal-mask',
                'description'      => 'A detoxifying charcoal mask that unclogs pores.',
                'price'            => 14,
                'sale_price'       => 11,
                'product_types'    => ['Oily', 'Combination'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/charcoal-mask',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 12,
                'category_id'      => 6,
                'title'            => 'Ceramide Barrier Moisturizer',
                'slug'             => 'ceramide-barrier-moisturizer',
                'description'      => 'Restores the skin barrier using ceramide complex.',
                'price'            => 13,
                'sale_price'       => null,
                'product_types'    => ['Dry', 'Sensitive'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/ceramide-cream',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 13,
                'category_id'      => 4,
                'title'            => 'Hyaluronic Hydration Serum',
                'slug'             => 'hyaluronic-hydration-serum',
                'description'      => 'Deep hydration serum with triple hyaluronic acid.',
                'price'            => 12,
                'sale_price'       => null,
                'product_types'    => ['Dry', 'Normal'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/hyaluronic-serum',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 14,
                'category_id'      => 2,
                'title'            => 'Nourishing Day Cream',
                'slug'             => 'nourishing-day-cream',
                'description'      => 'A rich nourishing cream ideal for daily moisturizing.',
                'price'            => 16,
                'sale_price'       => 13,
                'product_types'    => ['Dry', 'Normal'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/day-cream',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 15,
                'category_id'      => 7,
                'title'            => 'Tinted Daily Sunscreen SPF 30',
                'slug'             => 'tinted-daily-sunscreen-spf-30',
                'description'      => 'A lightweight tinted sunscreen for daily protection.',
                'price'            => 14,
                'sale_price'       => null,
                'product_types'    => ['All Skin Types'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/tinted-sunscreen',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
            [
                'sort_order'       => 16,
                'category_id'      => 5,
                'title'            => 'AHA/BHA Exfoliating Toner',
                'slug'             => 'aha-bha-exfoliating-toner',
                'description'      => 'Chemical exfoliating toner that smooths and clears skin.',
                'price'            => 12,
                'sale_price'       => 10,
                'product_types'    => ['Oily', 'Combination'],
                'image'            => 'https://dummyimage.com/600x600/cccccc/000&text=Product+Demo+Image',
                'affiliate_link'   => 'https://amazon.com/exfoliating-toner',
                'affiliate_source' => 'Amazon',
                'status'           => ProductStatus::ACTIVE->value,
                'created_by'       => 1,
                'updated_by'       => 1,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
